### ISSUE TITLE
How to get Invitation code to register

### ISSUE THREAD

**Issue by Smallkan** [Lunik/Lunik-Torrent#108]
I have already installed and configured several times, both in Linux Ubuntu, CentOS, and Herokuapp Codeanywhere, I changed the invitation key and can not register nor log, someone help me!

**Comment by Lunik** [comment]
You need to understand that there is a différence between the `invitation key` that is in the configuration. And the `invitation code` that you genrate.

Here from what I see, you need the invitation code.
See [here](https://github.com/Lunik/Lunik-Torrent#register) for more information tu generate your `invitation code`
You can also use the script in `scripts/getinvite.sh`

**Comment by Smallkan** [comment]
Great !, works on Linux. But one more question ... how to do the same thing in Herokuapp?

Thanks!

**Comment by Lunik** [comment]
On the [README](https://github.com/Lunik/Lunik-Torrent#heroku), you can deploy it to heroku.
(You need to redeploy it because I updated it).
Then Heroku ask you to choose your `Invitation Code`.

Once everything is deployed, Follow [this section](https://github.com/Lunik/Lunik-Torrent#-infos-) in the README.
Do something like:
```
$ curl --data "invitationKey=MY_INVITATION_KEY" http://MY_APP.herokuapp.com/auth?todo=invite
```

**Comment by Smallkan** [comment]
Okay, I added again and asked the INVITATION CODE, already added, but the command that begins with curl, how to run it has no way to access SSH on Heroku?

**Comment by Lunik** [comment]
You can run it from your computer.

**Comment by Smallkan** [comment]
Lunik, thank you.

Well, I still use Windows, so I used the SSH Codeanywhere by changing the address in getinvite.sh and key in config.json then ran the curl command and it generated a valid key.

It's working!

Thank you for the support!

**Comment by Lunik** [comment]
You're welcome

**Comment by hackyack** [comment]
"Error
"Wrong User, Pass or  Invitation"

How i can Get User : Pass

**Comment by Lunik** [comment]
You need to be more specific otherwise I can't help you 😅

**Comment by torrentleech1** [comment]
please i need to invide code.

**Comment by Lunik** [comment]
https://github.com/Lunik/Lunik-Torrent/issues/108#issuecomment-241199266
