### ISSUE TITLE
What is Invitation Key ?

### ISSUE THREAD

**Issue by chethan-ramesh** [Lunik/Lunik-Torrent#136]
Hi,

Can you please explain how to generate the Invitation Code while deploying on Heroku. Since this has to be done before deployment & is mandatory.

![inv_code_issue](https://cloud.githubusercontent.com/assets/20771140/18226035/19639eac-721f-11e6-97cd-1b69c59fceb2.jpg)

Thanks

**Comment by Lunik** [comment]
Hi ! 
I understand It's not very clear. You can choose what ever you what as invitation key.
It allow you to generate invitation code in the future to register to your app.

**Comment by chethan-ramesh** [comment]
Thanks for the reply.

So, I can choose anything as an Invitation Code, or does it have a specific fromat?

**Comment by Lunik** [comment]
Yes ! It's like a passord.
