### ISSUE TITLE
How to use the App to download torrents (+more)

### ISSUE THREAD

**Issue by alicoder** [Lunik/Lunik-Torrent#138]
I installed this script and in CentOS and run it get me:
```
[Server] [Info] Server listening at port 8080
You have the latest version of lunik-torrent (current: 2.18.2)
```
and I registered new account and entered it but I found that what I can only do is creating folder and access it there is no any thing in the torrent tab.
also there is 2 errors in the console :
```
http://xx.xxx.xxx.xx:8080/%7B%7B%20info.poster%20%7D%7D Failed to load resource: the server responded with a status of 404 (Not Found)
http://xx.xxx.xxx.xx:8080/%7B%7B%20e.cover%20%7D%7D Failed to load resource: the server responded with a status of 404 (Not Found)
```

How can I fix this ?

**Comment by Lunik** [comment]
Everything seems normal.

The torrent tab only show active torrents.
To download torrent, you need to put a *magnet* or a *torrent link* in this input ![torrent-input](https://puu.sh/r0YJK/0277e7f8c5.png).
Then the *search* button should switch to *start*
Then it should appear in the torrent tab. Once finished you will find the file in the direcoty tab.

The two errors that your are showing come from [index.html#L103](https://github.com/Lunik/Lunik-Torrent/blob/master/src/public/index.html#L103) and [index#121](https://github.com/Lunik/Lunik-Torrent/blob/master/src/public/index.html#L121)
`{{ e.cover }}` is a variable that is replaced by [Vue.js](https://vuejs.org/)
But sometimes the page load faster than *Vue.js* and this error can appear.
Nothing to worry (I will fix it someday...)

I hope I was clear :)

**Comment by alicoder** [comment]
Yes very clear, thanks.
Now I have a new problem when I put magnet or a torrent link in that input.
I got an error 500 (Internal Server Error) and that in the ssh
 `TypeError: Object function Object() { [native code] } has no method 'assign at CPBAPI.Search .....'`

**Comment by Lunik** [comment]
Humm I see, did the button switch from *search* to *start* before you click on it ?
If no, this is a very old bug ! The button didn't update on `copy/paste`.
Add and remove space it should work.

Your error show that the client send *search* request instead of *start* request :/

**Comment by alicoder** [comment]
yes that was it, it worked now and in the ssh  show download torrent and and Start.
But after that I got another error :D 
`buffer.js:705throw
TypeError('value is out of bounds');` 
and It shutdown the site
npm ERR! weird error 8
npm ERR! not ok code 0

**Comment by Lunik** [comment]
Oooh this seems bad ! But I can't do anything :/
It seems to come from a dependency [webtorrent](https://github.com/feross/webtorrent/) I gess.

**Comment by alicoder** [comment]
ah I see ,
Okay thank you for your help and the nice script.

**Comment by Lunik** [comment]
You're welcome :)
