### ISSUE TITLE
Unable deploy current Master on Heroku

### ISSUE THREAD

**Issue by kamakuba** [Lunik/Lunik-Torrent#146]
Seems problem in jquery version.

`...
      bower jquery#>=1.6                                  resolved https://github.com/jquery/jquery-dist.git#3.1.0
       bower                                              ECONFLICT Unable to find suitable version for jquery
       
       npm ERR! Linux 3.13.0-93-generic
       npm ERR! argv "/tmp/build_91dd730f18c932ff49ba7d484f631a02/Lunik-Lunik-Torrent-1727e0d/.heroku/node/bin/node" "/tmp/build_91dd730f18c932ff49ba7d484f631a02/Lunik-Lunik-Torrent-1727e0d/.heroku/node/bin/npm" "install" "--unsafe-perm" "--userconfig" "/tmp/build_91dd730f18c932ff49ba7d484f631a02/Lunik-Lunik-Torrent-1727e0d/.npmrc"
       npm ERR! node v5.11.1
       npm ERR! npm  v3.8.6
       npm ERR! code ELIFECYCLE
       npm ERR! lunik-torrent@2.18.4 postinstall: `scripts/init.sh && bower install --allow-root`
       npm ERR! Exit status 1
       npm ERR!
       npm ERR! Failed at the lunik-torrent@2.18.4 postinstall script 'scripts/init.sh && bower install --allow-root'.
       npm ERR! Make sure you have the latest version of node.js and npm installed.
       npm ERR! If you do, this is most likely a problem with the lunik-torrent package,
       npm ERR! not with npm itself.
       npm ERR! Tell the author that this fails on your system:
       npm ERR!     scripts/init.sh && bower install --allow-root
       npm ERR! You can get information on how to open an issue for this project with:
       npm ERR!     npm bugs lunik-torrent
       npm ERR! Or if that isn't available, you can get their info via:
       npm ERR!     npm owner ls lunik-torrent
       npm ERR! There is likely additional logging output above.
       
       npm ERR! Please include the following file with any support request:
       npm ERR!     /tmp/build_91dd730f18c932ff49ba7d484f631a02/Lunik-Lunik-Torrent-1727e0d/npm-debug.log
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       Some possible problems:
       
       - Node version not specified in package.json
       https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed`

**Comment by Lunik** [comment]
The error come from JQuery conflict on installing `bower`packages.
`popupjs` is using `3.x` and I was using `2.x`
Should be fixed on master@89fc31ae9741a57ae56866bfe35612c9d7e50da6
