### ISSUE TITLE
Get invitation exemple not working

### ISSUE THREAD

**Issue by kamakuba** [Lunik/Lunik-Torrent#152]
After deploy on heroku when i try to get invite
`curl -s --data "invitationKey=P@ssw0rd" http://xxx.herokuapp.com/auth?todo=invite`
obtain: `{"err":"Missing Invitation Key."}`

Content of configs/config.json (add some `<cr>` for more visability):
`[root@hero xxx]# heroku run bash
Running bash on ⬢ xxx... up, run.9946
~ $ cat configs/config.json
{
  "autoUpdate": true,
  "log": {
    "path": "logs/"
  },

'  "client": {
    "downloads": "downloads/",
    "updateTimeout": 3000,
    "timeout": 30000,
    "maxTry": 3
  },

'  "server": {
    "port": 8080,
    "invitationKey": "P@ssw0rd"
  },

'  "directory": {
    "path": "files/"
  },

'  "torrent": {
    "downloads": "downloads/",
    "scanTorrent": "torrents.txt",
    "max": 3
  }
}
`

**Comment by kamakuba** [comment]
i'm try to use more simplest pass:
`  },
  "server": {
    "port": 8080,
    "invitationKey": "password"
  },
`
but result - the same: `curl --data "invitationKey=password" http://xxx.herokuapp.com/auth?todo=invite
{"err":"Missing Invitation Key."}`

**Comment by Lunik** [comment]
Try using `curl --data "invitationkey=password" http://xxx.herokuapp.com/auth?todo=invite`
It's not `invitationKey` but `invitationkey`
(The README have been fixed)

**Comment by kamakuba** [comment]
it working!!!

**Comment by Lunik** [comment]
:)
