### ISSUE TITLE
How to install the App ?

### ISSUE THREAD

**Issue by smartHarsh** [Lunik/Lunik-Torrent#157]
sir i have installed docker as instructed and made an account on heroku with an encryption key. what is the username and password .And how to register an username and password

**Comment by Lunik** [comment]
I think the Documentation is not very clear 😓
But if you want to install it you have 3 ways:
+ [With Git](https://github.com/Lunik/Lunik-Torrent#git)
+ [With Heroku](https://github.com/Lunik/Lunik-Torrent#heroku)
+ [With Docker](https://github.com/Lunik/Lunik-Torrent#docker)

For the Docker and Git solution you must be on your personnal server. If you can't have a dedicated server or VPS use the Heroku solution.

When the server is setup, you can't try to access it form you browser. Then you can register and login.
About register now. You need to generate invitation code by following the [Register section](https://github.com/Lunik/Lunik-Torrent#register)

Then you should be able to use the app.
