### ISSUE TITLE
Heroku don't store my data

### ISSUE THREAD

**Issue by Getsuga286** [Lunik/Lunik-Torrent#160]
I registered onto lunik torrent, but after about an hour or so, I try to login again, but I cannot.
Where am I going wrong?

**Comment by Lunik** [comment]
If you're on heroku. Heroku don't save all application data. Including your passwords.
Try to register again

**Comment by raikikon** [comment]
how to fix heroku then , please help me create a extrenal database source

**Comment by Lunik** [comment]
Heroku has a container based infrastructure. You can't store any data.
I have created heroku deployment because someone ask it #4. But in my opinion it's not the best deployment.

**Comment by cleme29** [comment]
You should put that in your doc, to make people aware of this behavior of heroku :)

**Comment by Lunik** [comment]
Actually is you only have one heroku app, you can use [kaffeine](http://kaffeine.herokuapp.com/) to keep your app up 24/24
