### ISSUE TITLE
Docker Help

### ISSUE THREAD

**Issue by Getsuga286** [Lunik/Lunik-Torrent#161]
I followed your instructions in setting up lunik-torrent for docker.
What am I supposed to do after that?
I am new to docker
I can see lunik-torrent listed in "docker ps -a"
I do "docker start <name>"
But then I check "docker ps" and it is not listed there, it is not started.
What am I supposed to do?

**Comment by Lunik** [comment]
Can you show me the logs ?
`docker logs <container_id>`
