### ISSUE TITLE
How to create a invitiation code on heroku

### ISSUE THREAD

**Issue by usertex** [Lunik/Lunik-Torrent#165]
I have a problem to get a invitiation code, how to get one? 
I put "123A" as the code when I click register nothing happens.
http://i.imgur.com/qBUrtbd.png
http://i.imgur.com/Ndqy3AZ.jpg
http://i.imgur.com/KqaH6qu.png

**Comment by Lunik** [comment]
`Invication code` and `Invitation key` are not the same !
`Invitation key` is for generating `invitation code`
To generate an `invitation code` follow [this instructions](https://github.com/Lunik/Lunik-Torrent#register)

**Comment by usertex** [comment]
To generate an invitation code I have to do these commands? I have almost no programming knowledge.
There's no way you remove this "login" and create a deployment to heroku?
I translated it by google, sorry if went bad.

**Comment by Lunik** [comment]
Actually there is no way to do it.

**Comment by Lunik** [comment]
#160
