### ISSUE TITLE
How to generate Invitation Code

### ISSUE THREAD

**Issue by Infy06** [Lunik/Lunik-Torrent#167]
I didn't understand your steps for creating invitation code please tell me how to do it on Windows i am confused please! ( i am using Heroku)
~Thank You

**Comment by Lunik** [comment]
When you have created your App on Heroku you have chosen an `Invitation key`right ?
![heroku](http://i.imgur.com/qBUrtbd.png)

Now that your app is runnig, use curl to generate the `invitation code`
```

**Comment by Infy06** [comment]
listen it's okay though its my fault only i dont understand curl first of all or anything  can u make a video for this it looks like you made an awesome thing and i really want to try lunik torrent please only if its possible and are you talking about this curl? https://curl.haxx.se/download.html please make a video 
thank you
