### ISSUE TITLE
Wrong username and password

### ISSUE THREAD

**Issue by Infy06** [Lunik/Lunik-Torrent#170]
okay so i got it working and its was working fine but the  moment idk a 60 gb game maybe (GtaV) i was automatically logged out from it and now i get message incorrect username/password is there any limit for using it or can we upload unlimited size torrents?

**Comment by raikikon** [comment]
herokuapp forgets everything  use my nologin one

**Comment by Infy06** [comment]
Umm can you give me please?

**Comment by raikikon** [comment]
https://github.com/raikikon/Lunik-Torrent/tree/heroku-nologin

**Comment by raikikon** [comment]
torrentxyz.herokuapp.com here the example

**Comment by Infy06** [comment]
And can we upload unlimited torrents? Coz k pillows no longer supports heroku and I really want this so please :)

**Comment by Infy06** [comment]
Jpillora *

**Comment by Lunik** [comment]
#160
