### ISSUE TITLE
Cannot generate invitation code deploying after on heroku!!!!!!!

### ISSUE THREAD

**Issue by hackevil** [Lunik/Lunik-Torrent#184]
Hi first of all thanks to lunik for this amazing stuff.
But what is the use of this stuff when many people cannot use because of the same problem "invitation code" cannot be generated because people like me who have no knowledge of coding cannot resolve it.
So it is a humble request to the dev and those people who know how to deploy it on heroku and to generate invitation code.If anyone know how to use it on heroku please make video of it that pleploe with know knowledge of coding can also use it without facing any problems.

**Comment by Lunik** [comment]
Checkout #165 and #167 and also the [README](https://github.com/Lunik/Lunik-Torrent#register)

**Comment by hackevil** [comment]
can u please make video of it how to deploy it on heroku and how to generate the invitation code.
Cause the curl is not working for me.

**Comment by Lunik** [comment]
The way to get the invitation code have been made easier ! :)
See [README](https://github.com/Lunik/Lunik-Torrent#-infos-)

**Comment by hackevil** [comment]
hi first of all thanks for your response.
I have launched it your app on Heroku and it was deployed perfectly and i used **lunik1** as the name and i used 12345678 as the **invitation key** now from here the trouble starts as it is mentioned on the register section of your app
![er1](https://cloud.githubusercontent.com/assets/23115256/20052859/d17bfa70-a4fb-11e6-99d7-d2ad6d654ae1.PNG)

now i want to ask that which one of them is correct.
**1**
![er2](https://cloud.githubusercontent.com/assets/23115256/20052942/3fc4bf80-a4fc-11e6-99a6-e7833e85656d.PNG)

**2**
![er3](https://cloud.githubusercontent.com/assets/23115256/20053010/9c1f49da-a4fc-11e6-8ee1-0219b9dfd254.PNG)
**3**
![er4](https://cloud.githubusercontent.com/assets/23115256/20053019/a5abc3a2-a4fc-11e6-8b86-4d54961a37e1.PNG)
**4**
![er5](https://cloud.githubusercontent.com/assets/23115256/20053031/b7bb86f4-a4fc-11e6-9781-b2b5c9080e8e.PNG)

So please respond me as soon as possible cause u dont how it is necessary to me so please reply fast and if may do me favor please if and only if you can generate a invitation key and register an account for me cause i have already provided the necessary details above and mail to me.

My E-mail=viv3k.kanaujiya@gmail.com

**Comment by Lunik** [comment]
I have just fixed it 07fe287459baa421ed50f11778b3815f9afa7c29 V2.20.2

**Comment by hackevil** [comment]
it is not working brother it just redirect me to the login page will u plz plz make a account on any lunik torrent cause it seems like it is impossible to generate the register key so please make a account for or u can make a video how to generate the register key on heroku.
And thanks for your reply

**Comment by Lunik** [comment]
Try to redeploy the application to the latest version !
It work for me, see https://testtgdsq.herokuapp.com/invitation?invitationkey=coucou

**Comment by hackevil** [comment]
hi thanks for your help now i am able to generate the invitation code for lunik but still i have some queries,
1.Is there limit on simultaneously download of torrent or no of torrent.
2.There is a bug in your torrent client that it cannot download files bigger than 10 GB.

I am not able to add torrents which are larger than 10 GB it sends me a message that torrent is added successfully and will begin in moments but the page just keep refreshing for hours. So, please fix it as soon as possible.

And thanks for your help:)

**Comment by Lunik** [comment]
+ For the limit of simultaneously download it's 3 by default in the [configs](https://github.com/Lunik/Lunik-Torrent/blob/master/configs/config.default#L9)

+ For the file larger than 10GB I don't see were it come from. Open a new issue with heroku logs thanks ;)
