### ISSUE TITLE
Cannot select files sometimes after the torrent is downloaded.

### ISSUE THREAD

**Issue by hackevil** [Lunik/Lunik-Torrent#190]
![vivek-11-11-2016-17-45-12](https://cloud.githubusercontent.com/assets/23115256/20215183/a28d7636-a838-11e6-97dd-b223fd6e83a9.gif)
Hi today i was using lunik but suddenly i was unable to select files which are downloaded on the servers due to this i am not able to download my files.You may be thinking that the gif is of someones else lunik's
but i found this issue on my lunik then i thought that let me try on another lunik but the issue was also on that.
So, please fix as soon as possible.
Thanks in advance:}

**Comment by Lunik** [comment]
I don't know from where this error come from :/ 
For now if you have this issue, you can click on the icon at the end of the file name to copy the link of the file. Open a new window and paste the url to downloadit.

**Comment by cleme29** [comment]
It's maybe your browser or addons that you add.
Try with an another browser or in a private session :)

**Comment by hackevil** [comment]
Thanks buddy for your help truly you made my day today thanks for your all help.
Keep it up,you are the best :+1:
