### ISSUE TITLE
How to disable registration and login?

### ISSUE THREAD

**Issue by cinetube** [Lunik/Lunik-Torrent#194]
How to disable registration and login?

**Comment by Lunik** [comment]
It's not supported yet

**Comment by UlisesOcana** [comment]
Please add public download link would be very useful to share a file

**Comment by decxffr** [comment]
Please add public download link would be very useful to share a file
yes.

**Comment by Lunik** [comment]
#249

**Comment by Lunik** [comment]
By default, authentification is disabled.
You can enable it in the config file
