### ISSUE TITLE
Heroku Aplication Error

### ISSUE THREAD

**Issue by usertex** [Lunik/Lunik-Torrent#201]
Helo, when i deploy to heroku a get this problem: 
Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.

**Comment by Lunik** [comment]
Show me your logs please.

**Comment by hackevil** [comment]
H i today i also faced this issue so i am sending u a screenshot of the application log
![capture](https://cloud.githubusercontent.com/assets/23115256/20867099/8e4d4002-ba62-11e6-840e-aebc8b94991a.PNG)

**Comment by Lunik** [comment]
There is not the begining of the error I can't help you with this. Try to show me more lines...

**Comment by Lunik** [comment]
I figured out where the error came from. I will fix it before tonight

**Comment by Lunik** [comment]
Should be fixed since the last commit

**Comment by hackevil** [comment]
Thanks for your response fix it ASAP :+1:

**Comment by Lunik** [comment]
It is fixed ! :)
Just redeploy ;)

**Comment by hackevil** [comment]
Thanks now it is working awesome :)

**Comment by usertex** [comment]
Thanks!
