### ISSUE TITLE
Private torrents

### ISSUE THREAD

**Issue by usertex** [Lunik/Lunik-Torrent#203]
Hello Lunik, its possible to you add a option to download torrents from private trackers? I download 95% of me content from private trackers, thanks, you have created the best plataform to download torrents! Realy thanks.
Sorry for my poor english.

**Comment by Lunik** [comment]
Hum, the issue with private trackers is that they need authentification to the the .torrent file. What you can do is :
+ Download the .torrent file on your computer
+ Upload it to [TinyUpload](http://www.tinyupload.com/)
+ Click on the link "You can download it from address: ..."
+ Copy the link "To download file click the link below: ..."
+ Paste it on my app

**Comment by usertex** [comment]
Unfortunately I did not succeed. I tried with several but none worked, once again thanks for the feedback.

**Comment by Lunik** [comment]
Damned !
