### ISSUE TITLE
Cannot GET /auth/invitation?masterKey=****

### ISSUE THREAD

**Issue by ilham88** [Lunik/Lunik-Torrent#210]
Create an invitation code
Goto to http://myapp.com/auth/invitation?masterKey=MY_MASTER_KEY

And
I can't create invitation code

Cannot GET /auth/invitation?masterKey=****** (my master key)

Please help me.. :(

**Comment by hackevil** [comment]
Hi toady i also encountered this issue on my app i thought that it is a issue of heroku so created a new one but still it showing the error when the invitation key is requested plz fix it asap :(
Thanks in advance!!

**Comment by Lunik** [comment]
First of all, it is not `/auth/invitation` anymore since 3.0.0 [see here](https://github.com/Lunik/Lunik-Torrent#register). Now it is `/auth/invite`.
Secondly there was a mistake on heroku when setting the master key. It should be fixed by now (3.0.1)

**Comment by hackevil** [comment]
thanks buddy for fixing this issue!!
