### ISSUE TITLE
How to increase no of simultaneously torrent downloads

### ISSUE THREAD

**Issue by viveksahh** [Lunik/Lunik-Torrent#219]
Plz explain how to increase no of simultaneously download of torrents.

**Comment by Lunik** [comment]
Since last version, there are no limits anymore. But if you are in 3.0.2 or under, modify the [configuration](https://github.com/Lunik/Lunik-Torrent/blob/dbd5eeec4a506d0e0862cf5334aacb9185fce957/configs/config.default#L26): 
`torrent.max` to the amount of your choice
