### ISSUE TITLE
Need help!!!

### ISSUE THREAD

**Issue by vivekkanaujiya** [Lunik/Lunik-Torrent#222]
Hi today i deployed your app on heroku and it was really amazing to see that it was working perfect without any glitch, but there is problem that is your app do not provide direct download links it requires the login details to download files, but i want to upload the downloaded torrents to some file hosting sites via remote url but i cannot!!!

Is there any way to do it or not please reply ASAP
Thanks in adavnce!!!

**Comment by Lunik** [comment]
actually, there is no way to upload `.torrent` file. There is two way I see for now:
- Use [tinyupload](tinyupload.com), see [here](https://github.com/Lunik/Lunik-Torrent/issues/203) for more details 
- Use [torrent2magnet](http://torrent2magnet.com/), it generate a magnet url that you can use in my app.

**Comment by vivekkanaujiya** [comment]
well thanks for ur reply but dont understand my question i want to say that i cannot upload cached torrent files via remote url because ur app do not gives the direct link to download it requires the login details to download.
So is there any way to upload the cached files to file sharing sites or google drive via remote url for backup purpose.

**Comment by Lunik** [comment]
no there is not

**Comment by mikan01** [comment]
I too need to backup my files to cloud, but Lunik-torrent doesn't give direct url. Is there any any to do it? Or can you implement this feature in future release? Thanks.

**Comment by Lunik** [comment]
Why don't you download it and then put it on the cloud ?

**Comment by mikan01** [comment]
Because it takes more time due to slow internet speed. Cloud backup is quick and we can stream the content anytime. :)
