### ISSUE TITLE
Direct link download

### ISSUE THREAD

**Issue by hackevil** [Lunik/Lunik-Torrent#249]
hey first of all thanks to u for this amazing stuff.
I just wanted to say that why dont you add hotlink to the files cause whenever i add link of a file to idm like download managers it just download a webpage, is there not any way to solve it.

**Comment by Lunik** [comment]
I see what you means, I want this feature to since a long time ! I will think about it :)

**Comment by Lunik** [comment]
Working on it here #254

**Comment by Lunik** [comment]
Implemented
