### ISSUE TITLE
How to deploy it to arukas.io

### ISSUE THREAD

**Issue by hackevil** [Lunik/Lunik-Torrent#251]
can you please tell me hoiw to deploy it to arukas.io

**Comment by Lunik** [comment]
It seems to be docker hosting, try to look [this](https://github.com/Lunik/Lunik-Torrent#with-docker)
And use [this image](https://hub.docker.com/r/lunik/lunik-torrent/)

**Comment by hackevil** [comment]
@Lunik Which port to use btw thanks for removing login and enabling the hotlink feature

**Comment by Lunik** [comment]
It should be `8080`

**Comment by hackevil** [comment]
thanks it worked you are genius dude.

**Comment by hackevil** [comment]
well i just found few bugs, that is 
it do not fetch some magnet links i dont know why but the magnet links are working fine in my torrent client,what is the reason behind it.

**Comment by hackevil** [comment]
![screenshot 6](https://cloud.githubusercontent.com/assets/23115256/24799979/c125c9e4-1bbb-11e7-8fe8-1194ae8e7a1b.png)
It seems like they have started to block your script a moment ago it was working fine but now they just stopped.

**Comment by Lunik** [comment]
They are redirecting you to https from what I know. By default, there is no HTTPS enable
try with only http

**Comment by hackevil** [comment]
what about the magnet fetching problem??

**Comment by Lunik** [comment]
If you have the hand on the `config.json` file, you can change the value of [this line](https://github.com/Lunik/Lunik-Torrent/blob/master/configs/config.default#L27) to increase the timeout of a torrent

**Comment by Lunik** [comment]
I have increase the timeout for torrent to 5 minutes
Wait few minutes until docker have build the Image and then retry

**Comment by hackevil** [comment]
@Lunik Have u limited the no of simultaneously active torrents, cause when i added my second torrent it was replaced by the one.
