### ISSUE TITLE
How to limit the download speed??

### ISSUE THREAD

**Issue by hackevil** [Lunik/Lunik-Torrent#261]
Please tell me ho can i limit the download speed of the client.

**Comment by Lunik** [comment]
It's planed here #112

**Comment by hackevil** [comment]
@Lunik u dont get my point i want to limit the downloading speed of the torrent not to limit the no of active torrents or the storage size.
I want to to limit the download speed of the files.
![capture](https://cloud.githubusercontent.com/assets/23115256/25555621/1881a60a-2d09-11e7-9aed-f852f7d8015e.PNG)

**Comment by Lunik** [comment]
I see !
