### ISSUE TITLE
why not download to Mega?

### ISSUE THREAD

**Issue by c21xdx** [Lunik/Lunik-Torrent#27]
why not download to Mega like this https://github.com/jpillora/node-torrent-cloud? and how can i install it on vps as a web page like it work on heroku? thanks

**Comment by Lunik** [comment]
Because It is not the purpose of this application. It store files into the server in order to manage the file from the web interface.
If you want to you Mega anyway see [Mega-Torrent](https://github.com/Lunik/Mega-Torrent).

If you want to install it on a VPS see [Lunik-Torrent installation](https://github.com/Lunik/Lunik-Torrent#-installation-).

**Comment by c21xdx** [comment]
i tried install Lunik-Torrent on coud9's ubuntu workspace, it show lots of error ater "npm run forever-start",
`> lunik-torrent@2.8.22 forever-start /home/ubuntu/workspace/Lunik-Torrent
> forever -a start src/index.js

sh: 1: forever: not found

npm ERR! Linux 4.2.0-c9
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v4.4.3/bin/node" "/home/ubuntu/.nvm/versions/node/v4.4.3/bin/npm" "run" "forever-start"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! lunik-torrent@2.8.22 forever-start: `forever -a start src/index.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the lunik-torrent@2.8.22 forever-start script 'forever -a start src/index.js'.
npm ERR! This is most likely a problem with the lunik-torrent package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     forever -a start src/index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs lunik-torrent
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls lunik-torrent
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/workspace/Lunik-Torrent/npm-debug.log`

and c9 has installed npm, so i has no use "npm install".

**Comment by Lunik** [comment]
In order to use forever-start, you need to install forever.
`npm install forever -g`

**Comment by c21xdx** [comment]
i tried again, 
![01](https://cloud.githubusercontent.com/assets/5766149/15652432/c388fe34-26b8-11e6-907a-277b5bd6b15a.jpg)

but still failed
![02](https://cloud.githubusercontent.com/assets/5766149/15652448/d8dc1960-26b8-11e6-82a2-78c11969f3a5.jpg)

i tried to run index.js , it show that
![03](https://cloud.githubusercontent.com/assets/5766149/15652491/2fa6f59e-26b9-11e6-955e-31dd40d152a5.jpg)

**Comment by Lunik** [comment]
You forget:
`npm install`
see [Lunik-Torrent installation](https://github.com/Lunik/Lunik-Torrent#-installation-).

**Comment by c21xdx** [comment]
thank so much, i will try  Mega-Torrent later

**Comment by Lunik** [comment]
You'r welcome ;)
