### ISSUE TITLE
Heroku Suspended! And how to use in Digital Ocean?

### ISSUE THREAD

**Issue by iamrohitmishra** [Lunik/Lunik-Torrent#287]
Well as of now if you deploy this on heroku your app will be restricted and you cannot access it console.

i was hoping you could add a set of directions on how to deploy it with digital ocean droplet.

**Comment by Lunik** [comment]
Create a NodeJS droplet and follow [this instructions](https://github.com/Lunik/Lunik-Torrent#with-git)

**Comment by Lunik** [comment]
There is a new version of Lunik-Torrent and it is called [Tcloud](https://github.com/Lunik/tcloud). You can follow [this inscrutions](https://github.com/Lunik/tcloud#standalone) to install it.

**Comment by iamrohitmishra** [comment]
thanks for super quick reply,! 

there is some issue while using standalone section instruction.
i have added a pdf to show all my steps, i cant figure it out as i dont know very much.

https://drive.google.com/open?id=0B-HwAGWdmLWtZjZ4N0Y0R09NTVE

**Comment by Lunik** [comment]
Try with a newest versions v0.4.13 (the latest) https://github.com/Lunik/tcloud/releases
Follow the step, everything should work
`npm install --production` prompt an error, but don't worry.

For any other questions on [Tcloud](https://github.com/Lunik/tcloud) please open a new issue [here](https://github.com/Lunik/tcloud/issues)

**Comment by iamrohitmishra** [comment]
thnx i used latest version and things worked fine.

after $ node server.js 
i get messeage server listening on 0.0.0.0:5000

now how do i access the application?
my adress is 139.59.82.158, is dosnt show anything . also i tried 139.59.82.158:5000 here too nothing

**Comment by Lunik** [comment]
Everything is working. Now you need to search around IPTables and Firewalld on your server to allow connection form outside on your server.
It's now out of my field and I can't help you more. Ask Digital Ocean community to allow your port (5000) on your server
