### ISSUE TITLE
Heroku account has been suspended, can't use anymore

### ISSUE THREAD

**Issue by hi00** [Lunik/Lunik-Torrent#288]
It appears that your app was suspended because you were trying to upload file sharing software. This is not allowed under the Heroku Acceptable Use Policy. https://www.heroku.com/policy/aup

I have been  suspended 4 accounts...................
Neither of these can create app at Heroku，is there anything like heroku this website? Thank you!
https://github.com/Lunik/Lunik-Torrent
https://github.com/Lunik/tcloud

**Comment by Lunik** [comment]
If you have been suspended is for a good reason. What you do with my app is not my concern.
