### ISSUE TITLE
files to .zip

### ISSUE THREAD

**Issue by atahanguner** [Lunik/Lunik-Torrent#29]
Hİ. How can i download torrent files to .zip?

**Comment by Lunik** [comment]
What do you mean by `docs` ?

**Comment by atahanguner** [comment]
I want a download all files for zip
How can i do this?

**Comment by Lunik** [comment]
When you are on [Lunik-torrent repo](https://github.com/Lunik/Lunik-Torrent). Seen the green button on the top-right of the page. Saying "clone or download". Click here and you can download it as .zip
