### ISSUE TITLE
Zip Support Please

### ISSUE THREAD

**Issue by Invictus95** [Lunik/Lunik-Torrent#291]
# Let's talk
[Let's Chat](http://chat.lunik.xyz/channel/lunik-torrent)
# Don't post Issue about:
  + invitationCode or invitationKey
    + Checkout [README](https://github.com/Lunik/Lunik-Torrent#register) first then [#165](https://github.com/Lunik/Lunik-Torrent/issues/165) and [#167](https://github.com/Lunik/Lunik-Torrent/issues/167)

Can you please add support for downloading whole torrent as zip file? i want to download few seasons from torrent which has around 20-25 episodes so it might be handy to get whole zip instead of downloading them one by one.

**Comment by Lunik** [comment]
This repository is deprecated
