### ISSUE TITLE
Heroku ?

### ISSUE THREAD

**Issue by BloodMan29** [Lunik/Lunik-Torrent#4]
Hi !
Would be awesome if you could put your project on heroku with a big button to deploy on :)
Thanks !

**Comment by Lunik** [comment]
I'm working on it :)
https://github.com/Lunik/Lunik-Torrent/tree/heroku-deploy

**Comment by Lunik** [comment]
Done :)
https://github.com/Lunik/Lunik-Torrent#heroku

**Comment by BloodMan29** [comment]
Thanks ! :D
